### ISSUE TITLE
NameValueList loses responsiveness on resizing

### ISSUE THREAD

**Issue by sumad200** [grommet/grommet-theme-hpe#323]
On resizing a NameValueList, it changes to a single column NameValueList when viewport width is 768px. However, on further resizing (at 576px to be precise), the NameValueList changes back to a 2 column NameValueList, which is not the case when using the default grommet theme.

HPE Theme at 400px
![image](https://user-images.githubusercontent.com/92201689/222150391-de6ec5b3-96de-4096-858d-a64051f8f540.png)

Grommet default theme at 400px
![image](https://user-images.githubusercontent.com/92201689/222153012-4135cab8-2c74-4936-b4be-c79a0663cae8.png)

**Comment by jcfilben** [comment]
Thanks for raising this issue. I think what is happening is that the hpe theme has an 'xsmall' viewport breakpoint and the grommet theme only goes down to the 'small' size. I suspect that in the nameValueList code we are checking for a size 'small' breakpoint and adjusting that breakpoint to display as a single column, but we don't do this for 'xsmall' so once we hit the 'xsmall' breakpoint in the hpe theme it reverts back to showing the list as 2 columns. We should fix this so that the 'xsmall' breakpoint displays the list as 1 column.

**Comment by taysea** [comment]
Related to https://github.com/grommet/grommet/issues/6944

**Comment by jcfilben** [comment]
Resolved by https://github.com/grommet/grommet/pull/7047
