### ISSUE TITLE
How to change the button primary background color from green?

### ISSUE THREAD

**Issue by biapar** [grommet/grommet-theme-hpe#356]
How to change the button primary background color from green?

**Comment by biapar** [comment]
I had to overload the green color.
"green!": "#AE173A",
      green: {
        dark: "#B43d4E",
        light: "#AE173A",
      },

**Comment by taysea** [comment]
Hi @biapar, grommet-theme-hpe is intended for use with HPE web applications so the theme is based on HPE brand colors and shouldn't be overridden if you are building for HPE purposes.

Are you building for a non-HPE app? If so, you might find Grommet's Theme Designer helpful to generate your custom theme: https://theme-designer.grommet.io/

Here are some other helpful Grommet theme resources as well:
- https://v2.grommet.io/globaltheme
- https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation

**Comment by biapar** [comment]
Hi,

I like the HPE theme, so I'm starting from it and I use the merge function to personalize it.

**Comment by taysea** [comment]
I see, thanks for clarifying. The `deepMerge` function is the right way to approach overriding a theme.

Just for your own awareness, grommet-theme-hpe is subject to change as HPE branding changes. If you want a more controlled theming experience on your side, I'd recommend you manage the entirety of your theme as opposed to deepMerging with the hpe one. This is up to you of course.

I'm going to close this ticket since it seems you were able to leverage the merge function.
