### ISSUE TITLE
Fix color contrast errors for "text" colors on certain backgrounds

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-theme-hpe#401]
These text color errors need to be resolved and released in a patch fix.

![Image](https://github.com/user-attachments/assets/40ce3aa0-db3b-4c3d-ad1d-b168da6d6df8)
![Image](https://github.com/user-attachments/assets/b99f2b4e-4aa2-4e4e-ae46-7cfe28c1e2db)

Deliverables:
- [ ] Work with a designer to establish new text colors (as close to existing colors as possible, just enough to achieve contrast requirements)
- [ ] File a PR to fix the colors

**Comment by KennyAtHPE** [comment]
After discussing with Taylor and Brittany, we will omit the status colors for now since they are only used as foreground colors currently.

A couple of suggestions for the text color changes. Our current text strong is #333333 or 80% black. To reach a 4.5:1 contrast with the purple and red light palette colors, the text color must be at least 82% black aka #2E2E2E . In the image, I have the lightest colors from left to right. If we want to have the most minimal change to our colors then I'd recommend #2E2E2E but I've also dropped in several options for colors in between text strong and #222222 (original suggestion).


![Image](https://github.com/user-attachments/assets/72f0a3d8-5be1-48e7-81dc-199e08cd3402)

If we do want to reconsider the status color as part of this then #2B2B2B/83% black is the minimum accessible color
