### ISSUE TITLE
Padding issue with RadioButtonGroup in FormField

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-theme-hpe#70]
When I use Grommet Designer (with latest HPE theme) to create a RadioButtonGroup inside a FormField, there is no padding/margin around the RadioButtonGroup.  I don't know if this is an issue with the Designer not supporting the appropriate attributes, or an issue with either FormField or RadioButtonGroup.

![image](https://user-images.githubusercontent.com/17883783/82241248-07997e80-98f9-11ea-999f-f0fbb4afbc08.png)

**Comment by ShimiSun** [comment]
I'm guessing this issue is driven from the NEXT branch, correct?

**Comment by ShimiSun** [comment]
Linking to WIP https://github.com/hpe-design/design-system/issues/518

**Comment by ecircenis** [comment]
Correct.  Next branch.

**Comment by halocline** [comment]
@ecircenis Theme updates were made to RadioButtonGroup this week which address this padding issue, plus align the styling closer to the designs in Figma.

**Work included:**
1. Padding within FormField content box
1. Spacing between input circle and label
1. Hover state styling
1. Selected option styling
1. Site documentation + variant examples

**Remaining work to complete alignment with Figma include:**
1. Add larger circle in the selected state
1. Focus behavior when using keyboard
1. Tightening up default vertical spacing between RadioButtons
1. Font-weight for RadioButton labels should be "Medium" rather than "Normal"

**Action Requested:** Can you please confirm this work resolves this padding issue?

[Grommet Designer](https://designer.grommet.io/radiobuttongroup?id=HPE-design-system-hpedesignsystem-hpe-com)
[Design System Site](https://design-system.hpe.design/components/radiobuttongroup)

**Comment by halocline** [comment]
I am going to close this issue. @ecircenis if this isn't resolved to your satisfaction, let us know and we will re-open.
